module.exports = (sequelize, DataTypes) => {

    const proposta_comissao = sequelize.define('proposta_comissao', {
        id_proposta: {
            type: DataTypes.INTEGER,
            primaryKey: true,
            autoIncrement:true
        },
        proposta:DataTypes.STRING, 
        parceiro:DataTypes.STRING, 
        cnpj:DataTypes.STRING, 
        supervisor:DataTypes.STRING, 
        valor_liberado:DataTypes.STRING, 
        tipo:DataTypes.STRING, 
        convenio:DataTypes.STRING, 
        comissao_inss:DataTypes.STRING, 
        comissao_port:DataTypes.STRING, 
        comissao_novo:DataTypes.STRING, 
        status:DataTypes.STRING, 
        calculo:DataTypes.STRING, 
        status_pagamento:DataTypes.STRING, 
        data_pagamento:DataTypes.STRING, 
        movimentacao:DataTypes.STRING, 
        data_liberacao:DataTypes.STRING, 
        status_calculo:DataTypes.STRING, 
        contrato:DataTypes.STRING, 
        conversor:DataTypes.STRING, 
        data_inclusao:DataTypes.STRING, 
        receita_liquida:DataTypes.STRING, 
        cpf_sup:DataTypes.STRING, 
        cpf_ger:DataTypes.STRING, 
        gerente:DataTypes.STRING, 
        cpf_quat:DataTypes.STRING, 
        quaternario:DataTypes.STRING, 
        valor_sup:DataTypes.STRING, 
        valor_ger:DataTypes.STRING, 
        valor_quat:DataTypes.STRING, 
        pct_sup:DataTypes.STRING, 
        pct_ger:DataTypes.STRING, 
        pct_quat:DataTypes.STRING, 
        cpf:DataTypes.STRING, 
        nome:DataTypes.STRING, 
        data_proposta:DataTypes.STRING, 
        parceiro_esteira:DataTypes.STRING, 
        produto:DataTypes.STRING, 
        regra:DataTypes.STRING, 
        tipo_func:DataTypes.STRING, 
        siglae_corrigida:DataTypes.STRING, 
        valor_solicitado:DataTypes.STRING, 
        valor_refin:DataTypes.STRING, 
        data_cadastro:DataTypes.STRING, 
        data_base:DataTypes.STRING, 
        mes:DataTypes.STRING, 
        data_sup:DataTypes.STRING, 
        data_ger:DataTypes.STRING, 
        data_quat:DataTypes.STRING, 
        projeto:DataTypes.STRING, 
        correntista:DataTypes.STRING, 
        prazo_contrato:DataTypes.STRING, 
        taxa:DataTypes.STRING, 
        banco:DataTypes.STRING, 
        classificacao:DataTypes.STRING, 
        id_calculo:DataTypes.STRING, 
        pontuacao:DataTypes.STRING, 
        valor_pontuacao:DataTypes.STRING, 
        semana:DataTypes.STRING, 
        pct_tabela:DataTypes.STRING, 
        saldo_devedor:DataTypes.STRING, 
        parcela_total:DataTypes.STRING, 
        parcela_vencida:DataTypes.STRING, 
        parcela_vencer:DataTypes.STRING, 
        portabilidade:DataTypes.STRING, 
        data_vigencia:DataTypes.STRING, 
        taxa2:DataTypes.STRING, 
        competencia:DataTypes.STRING, 
        data_alteracao:DataTypes.STRING, 
        responsavel:DataTypes.STRING, 
        seguro_parceiro:DataTypes.STRING, 
        data_seguro_parceiro:DataTypes.STRING, 
        seguro_supervisor:DataTypes.STRING, 
        data_seguro_supervisor:DataTypes.STRING, 
        seguro_gerente:DataTypes.STRING, 
        data_seguro_gerente:DataTypes.STRING, 
        status_seguro:DataTypes.STRING, 
        seguro:DataTypes.STRING,
    }, 
        {
        tableName: 'proposta_comissao',
        timestamps: false
    })
    return proposta_comissao;
};